name: google_maps_place_picker
description: A Flutter plugin which provides 'Picking Place' using Google Maps
  widget. (MB version)
version: 0.0.2
publish_to: none
#homepage: https://github.com/martin-braun/google_maps_place_picker_mb

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  google_api_headers: ^4.1.2
  google_maps_flutter: ^2.7.0
  google_maps_webservice:
    git:
      url: https://github.com/AdarshKSeeroo/google_maps_webservice.git
      ref: 0.0.1

  provider: ^6.1.2
  tuple: ^2.0.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null

dependency_overrides:
  http: ^1.2.1

false_secrets:
 - /example/lib/keys.dart
 - /example/android/app/src/main/AndroidManifest.xml
 - /example/ios/Runner/AppDelegate.swift
